---
- name: Deploy, configure, and populate Postgres 10
  hosts: database_servers
  become: true
  gather_facts: false
  tags:
    - database_servers
  roles:
    - role: firewall
      vars:
        firewalld_open_services:
          - postgresql

    - role: postgres
