---
- name: Deploy haproxy load balancer
  hosts: load_balancers
  gather_facts: false
  become: true
  tags:
    - load_balancers
  roles:
    - role: firewall
      vars:
        firewalld_open_service:
          - http
        firewalld_open_port:
          - "80/tcp"

    - role: haproxy
