---
- name: Play provision openstack instance
  hosts: control_node
  connection: local
  gather_facts: false
  tasks:
    - name: Create instances
      os_server:
        cloud: "{{ item.openstack_cloud }}"
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        key_name: "{{ item.key_name }}"
        flavor: "{{ item.flavor }}"
        security_groups: "{{ item.security_groups }}"
        delete_fip: yes
        wait: no
        nics:
          - net-name: "{{ item.net_name }}"
        meta: "AnsibleGroup={{ item.metadata.AnsibleGroup }},deployment_name={{ item.metadata.deployment_name }}"
        userdata: |
          #!/bin/bash
      loop: "{{ instances }}"
