---
- name: Install flask packages
  package:
    name: "{{ __package }}"
    state: present
  loop: "{{ app_yum_packages }}"
  loop_control:
    loop_var: __package

- name: "Install flask repo {{ flask_repo }}"
  git:
    repo: "{{ flask_repo }}"
    dest: "{{ flask_home }}/{{ flask_app_name }}"
    update: yes
    force: yes
  tags:
    - git
