---
- name: Configure Postgres resources, user, database etc
  block:
    - name: Setup Postgres database(s)
      postgresql_db:
        name: "{{ __database.name }}"
        state: "{{ __database.state | default('present') }}"
      loop: "{{ postgres_databases }}"
      loop_control:
        loop_var: __database
    - name: Create Postgres user#(s)
      postgresql_user:
        name: "{{ __user.name }}"
        password: "{{ __user.password | default(omit) }}"
        encrypted: true # "{{ __user.encrypted | default(omit) }}"
        priv: "{{ __user.priv | default(omit) }}"
        db: "{{ __user.database | default(omit) }}"
        # role_attr_flags: "{{ __user.role_attr_flags | default(omit) }}"
        state: "{{ __user.state | default('present') }}"
      loop: "{{ postgres_users }}"
      loop_control:
        loop_var: __user
      no_log: "{{ postgres_user_no_log_state | default(false) }}"
  become_user: "{{ postgres_user }}"
