---
- name: Install Postgres packages
  package:
    name: "{{ __package }}"
    state: present
    disable_gpg_check: false
  loop:
    - "{{ postgres_rhel8_repo }}"
    - "{{ postgres_packages }}"
    - "{{ postgres_library }}"
  loop_control:
    loop_var: __package
