---
- name: Setup Postgres for remote password auth
  template:
    src: pg_hba.conf.j2
    dest: "{{ postgres_10_data_dir }}/pg_hba.conf"
  notify: restart_postgres

- name: Setup Postgres to listen on network interfaces
  lineinfile:
    dest: "{{ postgres_10_data_dir }}/postgresql.conf"
    line: "listen_addresses = '*'"
    insertafter: "#listen_addresses"
  notify: restart_postgres
